### PR TITLE
Added support for Mac OS X

### PR DESCRIPTION
**Pull request by jendas1**
Hi, I've added support for Mac OS X. It would be great if you merge this repos to able everybody installing ocamlfuse on mac.
Jendas

### CODE REVIEW

**Comment by sorin-ionescu** [comment]
And it works now? https://github.com/astrada/ocamlfuse/issues/2 is no longer needed?

**Comment by jendas1** [comment]
CPPFLAGS are still needed. I wasn't able to compile because of the error (running Mac OS X Mavericks): 
Unix_util_stubs.c:30:10: fatal error: 'sys/vfs.h' file not found 
So I updated header for mac [here](https://github.com/sorin-ionescu/ocamlfuse/pull/1/files#diff-09e70368126bc60bf8fb4175b13fec7eR30).

**Comment by sorin-ionescu** [comment]
It is desirable to make it seemingly compile without CPPFLAGS. If you could fix that, that would be awesome.

**Comment by jendas1** [comment]
I've added CPPFLAGS to makefile, you can now install just by running: `opam install ocamlfuse`
Is it what you want?

**Comment by sorin-ionescu** [comment]
Right, just make sure it doesn't break compilation on non-Mac. Maybe, wrap the definition in an OS check.

**Pull request merged**
